name: 'buildpackage'
on: [ pull_request ]

concurrency:
  group: build
  cancel-in-progress: true

jobs:
  pkgbuild:
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        branch: [stable, testing, unstable]
        runs-on: [ubuntu-22.04-arm, ubuntu-22.04]
        pkgname: [ lipstick-glacier-home-git ]
    runs-on: ${{ matrix.runs-on }}
    container:
      image: docker://manjarolinux/build:latest
    steps:
      - name: pkgbuild
        if: steps.skip.outputs.skip != 'true'
        uses: neochapay/action-makepkg@main
        with:
          pkgname: ${{ matrix.pkgname }}
          dispatch-token: ${{ secrets.DISPATCH }}
          branch: ${{ matrix.branch }}
          release: ${{ matrix.branch }}-$arch
          matrix.arch: $arch


